### ISSUE TITLE
Push  Argument list too long

### ISSUE THREAD

**Issue by gallexme** [ryanccn/attic-action#4]
my yaml:
```yaml
name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3  
    - name: Setup Attic cache
      uses: ryanccn/attic-action@v0
      with:
        endpoint: ${{ secrets.ATTIC_ENDPOINT }}
        cache: ${{ secrets.ATTIC_CACHE }}
        token: ${{ secrets.ATTIC_TOKEN }}
    - run: nix flake update
    - run: nix flake check --impure

```

Post Setup Attic Cache:
Post job cleanup.
Error: An error occurred trying to start process '/nix/store/xasbpkm59l734mh5d40jibqga8d9q6n-github-runner-.307.1/lib/externals/node16/bin/node' with working directory '/run/github-runner/machineid/repo/repo'. Argument list too long

any ideas?

**Comment by ryanccn** [comment]
I think this might be because too many store paths are being passed to the `attic push` command and it exceeds the system limit

https://github.com/ryanccn/attic-action/blob/7af24dd783f03def6110cad9bfb584347e5f4ae7/src/stages/push.ts#L24

**Comment by ryanccn** [comment]
@gallexme I made a fix in https://github.com/ryanccn/attic-action/commit/e78c87fc0e32a315c66c7e756caf798b2adaeb19, see if it works now

**Comment by gallexme** [comment]
```yaml

name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3  
    - name: Setup Attic cache
      uses: ryanccn/attic-action@v0.1.2
      with:
        endpoint: ${{ secrets.ATTIC_ENDPOINT }}
        cache: ${{ secrets.ATTIC_CACHE }}
        token: ${{ secrets.ATTIC_TOKEN }}
    - run: nix flake update
    - run: nix flake check --impure
   ```


```
Post job cleanup.
Error: An error occurred trying to start process '/nix/store/xasbpkm59l734mh5djibqga8d91q6n-github-runner-2.307.1/lib/externals/node16/bin/node' with working directory '/run/github-runner/machineid/repo/repo'. Argument list too long
##[debug]System.ComponentModel.Win32Exception (7): An error occurred trying to start process '/nix/store/xasbpkm59l734mh5d40jibqga8d91q6n-github-runner-2.307.1/lib/externals/node16/bin/node' with working directory '/run/github-runner/machineid/repo/repo'. Argument list too long
##[debug]   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
##[debug]   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
##[debug]   at System.Diagnostics.Process.Start()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken) in /build/src/src/Runner.Sdk/ProcessInvoker.cs:line 298
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken) in /build/src/src/Runner.Common/ProcessInvoker.cs:line 296
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken) in /build/src/src/Runner.Worker/Handlers/StepHost.cs:line 89
##[debug]   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage) in /build/src/src/Runner.Worker/Handlers/NodeScriptActionHandler.cs:line 192
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync() in /build/src/src/Runner.Worker/ActionRunner.cs:line 278
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken) in /build/src/src/Runner.Worker/StepsRunner.cs:line 290
##[debug]Finishing: Post Setup Attic cache
```

**Comment by gallexme** [comment]
jfi in the log it doesnt say
pushing to cache
so maybe it fails already at  const cache = core.getInput("cache"); one moment will send whole log

**Comment by gallexme** [comment]
cachix seems to write em to a file instead, maybe they faced a similar issue https://github.com/cachix/cachix-action/blob/master/src/main.ts#L60C97-L60C97
